services:
  - type: web
    name: node-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0   # Ensure the correct Python version
    build:
      - pip install -r requirements.txt   # Install Python dependencies
